apiVersion: v1
kind: Template
metadata:
    name: ruby-example
objects:
    - apiVersion: v1
      kind: ImageStream
      metadata:
          name: ${PARAM_IMAGE_NAME}
    - apiVersion: v1
      kind: BuildConfig
      metadata:
          labels:
              app: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
          selector:
              deploymentConfig: ${PARAM_APP_NAME}
          runPolicy: Serial
          source:
              type: Binary
          strategy:
              sourceStrategy:
                  from:
                      kind: ImageStreamTag
                      name: ruby27-rhel7-oracle:latest
                      namespace: openshift
          output:
              to:
                  kind: ImageStreamTag
                  name: ${PARAM_IMAGE_NAME}:latest
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
          labels:
              app: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
          selector:
              deploymentConfig: ${PARAM_APP_NAME}
          template:
              metadata:
                  labels:
                      deploymentConfig: ${PARAM_APP_NAME}
                      name: ${PARAM_APP_NAME}
                      environment: dev
              spec:
                  containers:
                      - name: ${PARAM_APP_NAME}
                        env:
                            - name: TZ
                              value: America/Argentina/Buenos_Aires
                        image: ${PARAM_IMAGE_NAME}:latest
                        ports:
                            - containerPort: 8080
                              protocol: TCP
                        resources:
                            limits:
                                cpu: 1000m
                                memory: 768Mi
                            requests:
                                cpu: 300m
                                memory: 512Mi
          triggers: []
          replicas: 1
          strategy:
              type: Rolling
    - apiVersion: v1
      kind: Service
      metadata:
          labels:
              app: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
          ports:
              - port: 8080
                protocol: TCP
                targetPort: 8080
          selector:
              deploymentConfig: ${PARAM_APP_NAME}
          sessionAffinity: None
          type: ClusterIP
    - apiVersion: v1
      kind: Route
      metadata:
          labels:
              app: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
          to:
              kind: Service
              name: ${PARAM_APP_NAME}
              weight: 100
          wildcardPolicy: None
parameters:
    - description: The application name
      displayName: Application name
      name: PARAM_APP_NAME
      value: ruby-example
      required: true
    - description: The image name
      displayName: Image name
      name: PARAM_IMAGE_NAME
      value: ruby-example
      required: true
